apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: dareg-api
    deployment-id: ${APP}
  name: dareg-server-${APP}
spec:
  replicas: 1
  selector:
    matchLabels:
      role: dareg-api-${APP}
  template:
    metadata:
      labels:
        role: dareg-api-${APP}
    spec:
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - image: ${DOCKER_IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}
          imagePullPolicy: Always
          name: dareg-api
          env:
            - name: COMMIT_DATE
              value: ${CI_COMMIT_TIMESTAMP}
            - name: COMMIT_HASH
              value: ${CI_COMMIT_SHORT_SHA}
            - name: APP_VERSION
              value: ${APP_VERSION}
            - name: APP_VERSION_DATE
              value: ${CI_COMMIT_TIMESTAMP}
            - name: APP_ENV
              value: ${APP}
          envFrom:
            - secretRef:
                name: ${APP}-secrets
          ports:
          - containerPort: 8080
            name: dareg-api
            protocol: TCP
          resources:
            requests:
              cpu: 0.2
              memory: "256Mi"
            limits:
              cpu: 0.5
              memory: "1024Mi"
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
